### ISSUE TITLE
Interactive Data Visualizations in Python

### ISSUE THREAD

**Issue by jenna-jordan** [carpentries-incubator/proposals#113]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

Interactive Data Visualizations in Python

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Yes: https://jennajordan.me/data-visualization-workshop/

3. Do your materials conform to our [Code of Conduct][coc]?

Yes (as far as I can tell)

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

Yes & Yes: https://github.com/jenna-jordan/data-visualization-workshop

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

N/A

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

Sure

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

jenna-jordan

8. Any other information you would like us to have or questions you have for us?

I'd appreciate feedback on the lesson. Also, right now there are no exercises, but I plan to add some in the near future - so ideas on exercises to add would also be appreciated.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thanks for submitting this lesson proposal @jenna-jordan!

You should have received an invitation to join a Team of maintainers for the lesson, as part of the carpentries-incubator organisation on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into carpentries-incubator, via the repository Settings. When that is done, I will make sure that you retain full Admin access to the repository.

As well as [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3), you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) to keep in touch with The Carpentries curriculum community.

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by jenna-jordan** [comment]
Great! I have completed the transfer of the repository. What are the next steps?

**Comment by tobyhodges** [comment]
Thanks @jenna-jordan, it is great to see this lesson join the Incubator! 

As mentioned in https://github.com/carpentries-incubator/data-visualization-workshop/issues/1 I have updated the repository permissions to give you full _Admin_ access, and I have also made you a Maintainer of the `data-visualization-python-maintainers` Team, so you should be able to add any collaborators on the lesson if and when you need to do so.

Some possible next steps for you to consider:

1. Adjust the https://jennajordan.me/data-visualization-workshop/ page to point to the new location for the lesson. If you need inspiration for that, take a look at the redirect set up on another lesson that was transferred into the Incubator last week: https://github.com/gitter-lab/ml-bio-workshop/blob/main/index.html
2. Consider opting in to have issues from the repository included in the table on [our Help Wanted page](https://carpentries.org/help-wanted-issues/). If you opt in, any issue you label `help wanted` on the repository will automatically be included in that table a few hours later. We point trainee Instructors and other community members to that page as a first point of reference for contributing to lessons, and it is a good way to attract spontaneous bug fixes and contributions. You can tag me in this thread to let me know if you want the lesson to be included in that issue listing.
3. Consider telling the community about your lesson by including it in the ongoing [Incubator Lesson Spotlight series](https://carpentries.org/posts-by-tags/#blog-tag-carpentries-incubator-spotlight) featured in The Carpentries blog and newsletter. Read more about that here: https://docs.carpentries.org/topic_folders/lesson_development/spotlight.html
4. Soon, we will open the open peer review process for lessons to be included in The Carpentries Lab. For lessons to be eligible for that review process, we ask that they have been "beta tested" i.e. taught by other Instructors so that you can determine how easily the lesson can be taken and taught by others and improve it based on their feedback. The Spotlight series mentioned above is a good way to find volunteers to test your lesson, and you can (also) send a message to the community via [TopicBox](https://carpentries.topicbox.com/groups/discuss) and Slack.
5. Finally, if there is anything else we can do to support you and the lesson, please feel free to get in touch on GitHub, Slack, email, or by scheduling a call with me on https://calendly.com/tobyhodges

I will close this issue now that the transfer is complete, but feel free to post here again if you have further questions.
