### ISSUE TITLE
Lesson - R and the tidyverse for working with datasets

### ISSUE THREAD

**Issue by Athanasiamo** [carpentries-incubator/proposals#127]
**1. What is the topic of your lesson or lesson proposal?**
Working with data can often be challenging. 
Data are rarely in the shape and format that is most convenient for your end product. 
Everyone working with data knows that there is a lot of work that goes into altering the data to make sure you can explore and highlight the interesting aspects of it. 
The lesson will focus on using the tidyverse set of R packages to learn how to plot, reshape, alter and summarise datasets

**2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.**
https://athanasiamo.github.io/r-tidyverse-for-working-with-data/

**3. Do your materials conform to our [Code of Conduct][coc]?**
Yes

**4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).**

https://github.com/Athanasiamo/r-tidyverse-for-working-with-data

**6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.**
Yes

**7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.**
Not right now, we can add later

**8. Any other information you would like us to have or questions you have for us?**
We have run this material in Oslo as a 3 hours x 3 days online course, and a 2 day in person course with a lot of positive feedback from learners. We have further ideas for more episodes, but believe this initial stage is ready for community feedback and that this is a lesson that many will find meaningful.

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @Athanasiamo!

I'll be happy to help you transfer the repository into the Incubator, but I have a question before we go ahead with that: the link you provided, to https://athanasiamo.github.io/r-tidyverse-for-working-with-data/, lands on a workshop webpage rather than the front page of a lesson site. In `_config.yml`, can you change the value of `kind` to `"lesson"` instead of `"workshop"` please?

Please let me know when that configuration has been changed and I will help you with the repository transfer, including updating the styling of the lesson to use The Carpentries Incubator template.

**Comment by Athanasiamo** [comment]
Hi @tobyhodges .

I've fixed the change from workshop to lesson, and I also fixed some files missing for rendering the website. Its not generating the schedule, for reasons I dont understand, but I'm sure we can get that fixed with the help of the community.

Thank you for approving it into the incubator!

**Comment by Athanasiamo** [comment]
Hi!

I'd like to bump this a little, in case its been lost in the stream of messages. Please let me know what else I need to fix to get it transferred into the incubator.

**Comment by tobyhodges** [comment]
Thanks for the bump, @Athanasiamo.

I spent some time trying to adjust the repository to build the lesson correctly but the process of creating a lesson site from a repository based on the workshop website template was more complicated than I had hoped. I discussed it with the other members of the Curriculum Team and we concluded that the easiest path for you to take would be to migrate the RMarkdown files for your lesson into a new repository. If you are going to do that, my recommendation is to adopt the new lesson infrastructure, The Carpentries Workbench: it is very well suited to RMarkdown, and the repository structure and dependency management is much more straightforward.

You can see an example of a lesson built with RMarkdown and the Workbench at https://fishtree-attempt.github.io/R-ecology-lesson/index.html

If you would like to take this approach, my colleague @zkamvar may be able to help you automatically transition your lesson to the Workbench (though I am not sure if the automated transition is possible from a repository based on the workshop webpage template like yours). Otherwise, there is a template repository you could use, after making some changes to the RMarkdown files for your episodes. Zhian and/or I can guide you through that process if needed.

Another Curriculum Team member, @MCMaurer was planning to contact you to discuss the common themes in your lesson and the new version of the Data Carpentry _Data Analysis and Visualisation in R for Ecologists_ lesson (linked above). He has now gone on paternity leave, so that conversation will be delayed a little, but I encourage you to take a look through what he has been building there, and to provide feedback/identify places where you might be able to contribute to his efforts.

**Comment by Athanasiamo** [comment]
Hi @tobyhodges 

I did a manual transfer, as it was not too hard and the automatic one didnt work as easily as expected.

I made a new repo, to be clean about it. 

https://github.com/Athanasiamo/r-tidyverse-4-datasets

It doesnt have learner profiles or instructor notes yet, but that can be fixed over time.

Let me know how it looks!

I've not looked thoroughly into the R for ecology repo, but the idea of this lesson was to make it domain free. I'll have a look more and see if some lessons from there can be used here. But we have run this course (and improved it every time) three times now, and have had really good learner feedback.

**Comment by tobyhodges** [comment]
Looks great @Athanasiamo! 

You should have received an invitation to join a Team of maintainers for the lesson, as part of the `carpentries-incubator` organisation on GitHub. After you have accepted that invitation, you will be able to transfer the lesson repository into the Incubator. I will then make sure you have the appropriate administrative access to your lesson.

Ideally, lessons in The Carpentries Incubator will use the Incubator styling, which can be applied to your lesson site by adjusting [the `carpentry` field to `"incubator"` in `config.yaml`](https://github.com/Athanasiamo/r-tidyverse-4-datasets/blob/ed48c072f27b7c10547b56e6e431ab2bbec89f08/config.yaml#L10). (This option is not currently documented in the templates - I have now opened pull requests to add it.) Making that change will ensure that the copyright notice, etc displayed on your lesson is appropriate, as well as making the site look consistent with other lessons in the Incubator that are using the Workbench.

As you have taught the lesson several times already, you should probably also update [the `life_cycle` field of `config.yaml`](https://github.com/Athanasiamo/r-tidyverse-4-datasets/blob/ed48c072f27b7c10547b56e6e431ab2bbec89f08/config.yaml#L23) to [`"alpha"` or even `"beta"`](https://cdh.carpentries.org/the-lesson-life-cycle.html), if you believe the lesson is ready for other instructors to teach and provide feedback. If the latter, I recommend that you submit the lesson for [an Incubator Lesson Spotlight feature](https://docs.carpentries.org/topic_folders/lesson_development/spotlight.html) in our blog and newsletter - this is a good way to ensure that the wider community is aware of the lesson and to invite them to help you develop it further.

Finally, to keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by Athanasiamo** [comment]
Hi!

Transfer is completed, but I also lost priveledges to rerun github actions etc, so cant seem to get the repo pages rebuilt.

The lesson is set to "alpha". We're running it again in September, and I'd love to get one more run in with minor changes before we change to beta. And It would give me time to make a blog or newsletter post about the lesson also. What an excellent idea! :)

**Comment by tobyhodges** [comment]
@Athanasiamo thank you 🙌 

GitHub Pages needed to be activated in [the repository settings](https://github.com/carpentries-incubator/r-tidyverse-4-datasets/settings/pages). I have done that now, so your lesson site should appear at https://carpentries-incubator.github.io/r-tidyverse-4-datasets/ in the next few minutes.

> And It would give me time to make a blog or newsletter post about the lesson also.

The submission process for the Incubator Lesson Spotlight is very easy - you do not need to write the blog post etc exactly. Instead, you fill in [a short online form to tell us about the lesson](https://docs.google.com/forms/d/e/1FAIpQLScJimGMtzqAFE-Tii-LvbfGZqtKj0OC4ken7_Qdlta8uZXAUA/viewform?usp=sf_link) and we use that to construct the blog post etc. We then ask you to review it and give us the 👍 before we publish the feature.

I will close this issue now that the transfer is complete, but I will still receive notifications so please respond below if you have any more questions. Or you can tag me on an issue on your lesson repository. Good luck with the next workshop in September!
