### ISSUE TITLE
Proposed lesson on modeling time series data for engineers.

### ISSUE THREAD

**Issue by jonathanwheeler01** [carpentries-incubator/proposals#134]
1. What is the topic of your lesson or lesson proposal?

The proposed lesson is a continuation of a lesson I've been developing in the incubator, [Time Series Analysis of Smart Meter Power Consumption Data](https://carpentries-incubator.github.io/data-management-pipelines-engineering/index.html) and <https://github.com/carpentries-incubator/data-management-pipelines-engineering>. This existing lesson is intended to introduce learners to Python Pandas, in particular methods related to working with time series data, with a final episode on simple linear regressions of time series data. The proposed lesson will go beyond simple linear regression to introduce other modeling methods and strategies, and will include more information about the scikitlearn library.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No.

**Comment by jonathanwheeler01** [comment]
Toby,

Thank you, I think both of the names you suggest for the repositories are
fine. Thank you very much for your help creating these!

Jon

**Comment by tobyhodges** [comment]
No problem, @jonathanwheeler01. Will you rename the `data-management-pipelines-engineering` repository (via the repository Settings page), or would you like me to take care of that?

Note that, when you change the name of the repository, GitHub will automatically redirect connections to the old _repository_ URL, but will not be able to redirect anyone to the new lesson site built from the renamed repository i.e. https://carpentries-incubator.github.io/data-management-pipelines-engineering/ will no longer work. 

If you have shared that URL with many other people, and you want to make sure that they can still find your lesson at its new URL, we can set up a redirect from another repository with the old name (see https://github.com/djhunter/r-ml-tabular-data/ for a recent example of something similar).

**Comment by tobyhodges** [comment]
Oh, and one more question: would you like to use the old lesson template for these two new lessons (like you have been using at https://carpentries-incubator.github.io/data-management-pipelines-engineering/), or [the new infrastructure, The Carpentries Workbench](https://carpentries.github.io/sandpaper-docs/) (entering _beta_, so not mature yet)?

**Comment by jonathanwheeler01** [comment]
Toby,

I requested my existing lesson to be included in the beta, so if I have the
option let's go ahead and use the new infrastructure for the two new
lessons. I will go ahead and rename the data-management-pipelines-engineering
repo.No worries about a redirect - I have shared that URL with some people,
but I'm currently the only maintainer on that lesson so the broken link
won't affect anyone.

Thanks!
Jon

**Comment by tobyhodges** [comment]
Hi @jonathanwheeler01, excellent! I have created a repository for this new lesson at https://github.com/carpentries-incubator/python-modeling-power-consumption. 

I added you as Admin for the repository, and also added the Maintainer Team from your other Incubator lesson, with Maintain-level access, because it sounded like it will be appropriate to have the same team with access to all three lessons. This means, if and when you gain other collaborators on these lessons, we will be able to add them to that team to grant them access to all the repositories at once. Happy to change that if you prefer, of course.

I will close this issue now that the repository has been created, but I will still receive notifications so please feel free to post back here if you have any follow-up questions or if you run into trouble accessing/using the new lesson repository.
