### ISSUE TITLE
Proposed lesson on clustering and classifying time series data

### ISSUE THREAD

**Issue by jonathanwheeler01** [carpentries-incubator/proposals#135]
1. What is the topic of your lesson or lesson proposal?

The proposed lesson is a third in a series focused on analyses of time series data using Pandas and Scikitlearn. The other two lessons in the series, of which one is already in development in the incubator, will introduce learners to Pandas and basic concepts and methods for time series analysis - seasonality, rolling means, etc., and will also demonstrate linear and non-linear regression models.

Both those lessons will use the same open dataset of power consumption (<https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.m0cfxpp2c>). This third lesson will use either the same dataset or an alternative dataset of solar irradiance (<https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.zcrjdfn9m>) to demonstrate methods for clustering and classifying data for the purposes of forecasting power consumption or, alternatively, solar power generation.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

No

**Comment by tobyhodges** [comment]
Hi @jonathanwheeler01, as discussed in #134 I have created a repository for this new lesson at https://github.com/carpentries-incubator/python-classifying-power-consumption, using the new Carpentries Workbench template (🎉) for a Markdown (as opposed to RMarkdown) lesson. 

I added you as Admin for the repository, and also added the Maintainer Team from your other Incubator lesson, with Maintain-level access, because it sounded like it will be appropriate to have the same team with access to all three lessons. This means, if and when you gain other collaborators on these lessons, we will be able to add them to that team to grant them access to all the repositories at once. Happy to change that if you prefer, of course.

I will close this issue now that the repository has been created, but I will still receive notifications so please feel free to post back here if you have any follow-up questions or if you run into trouble accessing/using the new lesson repository.
