### ISSUE TITLE
Machine Learning for Tabular Data in R

### ISSUE THREAD

**Issue by djhunter** [carpentries-incubator/proposals#136]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?
This lesson introduces a selection of machine learning techniques for analyzing tabular data, including random forests and gradient boosted trees.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.
The lesson has been written, revised, and piloted at UCSB. Here's the link to the lesson:
https://djhunter.github.io/r-ml-tabular-data/

3. Do your materials conform to our [Code of Conduct][coc]?
Yes

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).
Yes. The repository is here: https://github.com/djhunter/r-ml-tabular-data
The lesson is here: https://djhunter.github.io/r-ml-tabular-data/

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator? N/A

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.
Yes, please.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.
djhunter

8. Any other information you would like us to have or questions you have for us?
We ran a pilot of this workshop on August 16-18, 2022, at UCSB, and it was well received. Several Carpentry instructors at UCSB have provided feedback on the lesson, so we feel confident in designating it Beta.

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @djhunter.

You should have received an invitation to join a Team of maintainers for the lesson, as part of the carpentries-incubator organisation on GitHub. After you have accepted that invitation, you should be able to initiate the transfer into carpentries-incubator, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given “Maintain” privileges.

There are several other efforts ongoing to develop lessons on machine learning in the Incubator. If you would like to connect with some of the folks working on those other lessons, I recommend joining [the machine-learning channel on The Carpentries Slack workspace](https://swcarpentry.slack.com/archives/CKLUYLY2F) and/or the [machine-learning mailing list](https://carpentries.topicbox.com/groups/machine-learning). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/). 

Recently, there were a couple of breakout sessions at CarpentryCon about the possibility of more intentional coordination between these previously independent ML lesson efforts too. The recordings of those two sessions will soon be available on [our YouTube channel](https://www.youtube.com/c/TheCarpentries/videos).

To keep in touch with The Carpentries curriculum community more generally you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). 

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by tobyhodges** [comment]
Also, lessons in the Incubator should use the remote lesson theme, so that they can be styled consistently with the other Incubator lessons and have appropriate copyright information, etc. 

To switch to using the remote theme, you will need to make some changes to the `_config.yml` and remove several directories from the lesson repository. [See this pull request from another Incubator lesson for an example of how to make this switch](https://github.com/carpentries-incubator/metagenomics/pull/30/files) - there are a lot of changes in that PR because of all the files that are being deleted, but the crucial changes are to `_config.yml`. 

Feel free to reach out to me if you get stuck with this and need some help - I'm happy to open a pull request to take care of this for you if you prefer.

**Comment by djhunter** [comment]
Thanks Toby. I just initiated the transfer of the r-ml-tabular-data repo. To be clear, I should remove the entire `assets`, `_layouts`, and `_includes` directories, as well as change the `carpentry:` and `remote_theme:` fields in `_config.yml`? Sure, I can do that.

**Comment by tobyhodges** [comment]
I think that is all you will need to do, yes. Note that, if you extended the list of link targets in `_includes/links.md`, you can keep that file (it will be used _instead of rather an in addition to_ the version of the file at [carpentries/carpentries-theme](https://github.com/carpentries/carpentries-theme)).

**Comment by tobyhodges** [comment]
Thank you for transferring the repsoitory. I have restored your Admin access to the repository, updated the URL to the lesson pages from the repository, and also added a few new topics to the repository to help it show up in the lesson listings on our websites.

I will close this issue now that the repository has been transferred, but I will still receive notifications so please post back here if you run into any trouble getting settled into the Incubator.

**Comment by djhunter** [comment]
Thanks! Looks like I'm all set. Quick question: I'm assuming its safe to create a new repository in my github account now with the same name and put a redirect link to the incubator version?

**Comment by tobyhodges** [comment]
Good idea! That is the approach others have taken when they needed to point an existing audience to the new location.
