### ISSUE TITLE
[Proposal]:  Pipeline Training with Nextflow

### ISSUE THREAD

**Issue by NickSwainston** [carpentries-incubator/proposals#151]
### 1. Lesson Topic

Pipeline Training with Nextflow

### 2. Draft materials

https://github.com/ADACS-Australia/Nextflow_Training_2022B

### 3. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [ ] I need a new repository created

### 5. Transfer existing repository

- [X] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 6. Collaborators

@NickSwainston
@PaulHancock

### 7. Info/Questions

Paul and I have taught this lesson once. We designed the training for astronomers (Nextflow is mostly used by bioinformatics researchers) but hopefully, it is still general enough to be a useful lesson.

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to The Carpentries Incubator, @NickSwainston.

You should have received an invitation to join a team of maintainers for the lesson, as part of the `carpentries-incubator` organization on GitHub. 

The lesson is currently set up to use Software Carpentry styling, and is also based on [the template for workshop websites](https://github.com/carpentries/workshop-template) instead of [the equivalent for new lessons](https://github.com/carpentries/styles). The latter issue is not a blocker, and would probably be quite challenging to address now, but we would like all lessons in the Incubator to be using the appropriate styling: it helps to clarify to visitors that the lessons belong to their authors rather than to The Carpentries (we do not want to take credit for your work!). 

Please adjust the site configuration to use Incubator styling before you transfer it into the Incubator. You can do that by changing the value of the `carpentry` field to `"incubator"` in the `_config.yml` file.

After you have accepted the invitation to join the organisation, and adjusted the repository to use the Incubator styling, you should be able to initiate the transfer into `carpentries-incubator`, via the repository Settings. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given "Maintain" privileges.

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://swc-slack-invite.herokuapp.com/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by tobyhodges** [comment]
Your lesson will join [one other teaching Nextflow in the Incubator](https://github.com/carpentries-incubator/workflows-nextflow) - a lesson aimed more at the bioinformatics audience that you mentioned. I wonder if you are aware of that lesson, and whether there is any potential for the developers of the two lessons to work together to the mutual benefit of both lessons and their respective audiences?

**Comment by NickSwainston** [comment]
I have not changed the styling to a lesson yet. I have changed `carpentry` to `incubator` in the `_config.yml` and initiated the repository transfer.

I was not aware of the lesson. It does go into more detail about a few things, but it also does not cover a few topics that are useful for astronomers (introduction to data-driven pipelines, operators, metadata handling, and efficiently using supercomputers). We could combine the lessons, but it would become a large lesson. It would have two pipeline examples (one for bioinformatics and one for astronomy) and some of the nf-core stuff is not relevant to astronomy as the astronomy community has not started developing with nf-core yet.

**Comment by tobyhodges** [comment]
Thanks for transferring the repository, @NickSwainston. I noticed that some formatting issues were introduced when you transferred and renamed the repository, and I have opened [a pull request that I believe will fix the issue](https://github.com/carpentries-incubator/Pipeline_Training_with_Nextflow/pull/19). 

You may wish to create a placeholder repository that will redirect visitors to the old location of your lesson pages. [This is an example of such a redirection repository that someone else set up in the past](https://github.com/djhunter/r-ml-tabular-data).

I will close this issue now, but will still receive notifications from the thread, so please post back here or tag me in an issue on the lesson repository if you have any further questions.
