### ISSUE TITLE
[Proposal]: A TINY BIT OF foundational coding and data science skills to researchers' CONTEXT worldwide.

### ISSUE THREAD

**Issue by steltenpower** [carpentries-incubator/proposals#161]
### 1. Lesson Topic

data quality rules of thumb for researchers' context

### 3. Requirements for existing materials

- [ ] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [ ] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 4. New repository creation

- [X] I need a new repository created

### 5. Transfer existing repository

- [ ] my lesson meets both criteria in part 3 and I would like to transfer the repository to The Carpentries Incubator

### 7. Info/Questions

Researchers work in a context with not only researchers, but support, administration, etc.
If that context improves their data handling, that helps researchers.
Grow beyond the idea that data is something people interpret from a screen (as most using Excel do), as we don't want to make programmers cry. A focus on data quality.
I'm guessing this would take part of https://datacarpentry.org/spreadsheet-ecology-lesson/ and maybe some additional explanation of terminology. I got this idea after a research supporting colleague who I taught a carpentries course said: "I'll never code afterwards, but I now finally understand a lot of your remarks on interoperability (part of FAIR data)"

**Comment by steltenpower** [comment]
Thank you,

1:
Though I understand your suggestion for a title, as a research supporter it's not my direct colleagues providing data organized in a way 'that makes programmers cry', but basically a chunk of the rest of the organisation/world that seem to think that mixing raw data, editing, calculating, layout and colors in the same sheet is the right thing to do. Therefore my suggestion for the title would be something like
**"Data Organization in Spreadsheets to ease further processing"**.
At first I thought about "Data organization in Spreadsheets for everybody", but that could trigger thoughts like: I've been using Excel for ages, that's not for me.

2:
I'd like to start with a copy of the source of https://datacarpentry.org/spreadsheet-ecology-lesson/ please

**Comment by tobyhodges** [comment]
Thanks @steltenpower.

I have created the repository for you at https://github.com/carpentries-incubator/data-organisation-for-better-analysis - feel free to change the name. Please let me know if you do, so I can update our database.

You should have received an invitation to join the Developer Team for this lesson. I also granted you Admin access to the repository so you have full control.

The recommended next steps are a bit different than usual, because this is a copy of an existing, mature lesson:

1. **Adjust the `config.yaml` file:** this file contains global parameters for your lesson site. At minimum, you should adjust the following fields:
   - `carpentry` should be changed to `'incubator'`
   - `title`
   - `created` should be set to today's date, `'2023-05-25'`
   - `keywords`
   - `life_cycle` should be set to `'pre-alpha'` until the lesson is ready to be taught for the first time
   - `contact` should be your email address or another contact address you want to use
1. **Check annotations on the repository:** I have [added some keywords and other annotations to describe your lesson](https://cdh.carpentries.org/the-carpentries-incubator.html#topic-tags) in the _Topics_ field of the repository _About_ box (top-right of repo landing page). Please adjust them as you want.
1. **Adjust the `CODE_OF_CONDUCT.md`, `CONTRIBUTING.md`, and `LICENSE.md` files** as appropriate for your project.
1. **Update the README with [relevant information about your lesson](https://carpentries.github.io/lesson-development-training/26-external.html#readme)**, and add attribution to the DC lesson you are building from.

You might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) a helpful resource while working with The Carpentries lesson infrastructure. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and our [Collaborative Lesson Development Training curriculum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the incubator-developers list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the lesson-dev channel on The Carpentries Slack](https://swcarpentry.slack.com/archives/C3KUTT5V3).

I will close this issue now that the repository is created, but I will still receive notifications so please post back here if you have any questions!
