### ISSUE TITLE
[Proposal]: Performance Profiling & Optimisation (Python)

### ISSUE THREAD

**Issue by Robadob** [carpentries-incubator/proposals#195]
### 1. Lesson Topic

Performance Profiling & Optimisation (Python)

### 2. Lesson Language

English

### 3. Draft materials

https://github.com/RSE-Sheffield/pando-python
https://rse.shef.ac.uk/pando-python/

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [X] I need a new repository created

### 6. Transfer existing repository

- [x] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@robadob

### 8. Info/Questions

Please **fork the draft materials when creating the new repository**, so that GitHub tracks the relationship and how ahead/behind the repo gets. I intend to maintain the original draft in parity with the fork, as it includes some Sheffield-specific pages around signing up to attend etc.

The existing "draft materials" use a custom Varnish to match the university of Sheffield's branding (where it was funded/developed). This isn't a well documented feature of Workbench, so I'm not sure whether that's permitted to stay in the incubator version (I'm not terribly fussed either way).

**Comment by tobyhodges** [comment]
Hey @Robadob! Thank you for submitting this lesson to The Carpentries Incubator.

You should have received an invitation to join a Team of maintainers for the lesson, as part of the `carpentries-incubator` organization on GitHub. After you have accepted that invitation, you should be able to fork the repository yourself into `carpentries-incubator`. When that is done, I will make sure that you retain the appropriate level of access to the repository: you will be given full administrative rights, and the collaborators you listed above will be given "Maintain" privileges.

> The existing "draft materials" use a custom Varnish to match the university of Sheffield's branding (where it was funded/developed). This isn't a well documented feature of Workbench, so I'm not sure whether that's permitted to stay in the incubator version (I'm not terribly fussed either way).

Indeed! Improving that documentation is a task on my list. Maybe best to adjust the 'branding' on the Incubator repo back to `carpentry: "incubator"` so that it is easier to distinguish between the general purpose version of the lesson here, and the Sheffield-specific version you will be maintaining in parallel?

To keep in touch with The Carpentries curriculum community you may find it useful to join [the `incubator-developers` list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the `lesson-dev` channel on The Carpentries Slack](https://carpentries.slack.com/archives/C3KUTT5V3). Joining the Slack channel requires that you first [become a member of that workspace](https://slack-invite.carpentries.org/).

I will leave this issue open until the transfer has been completed. If you have any questions about the process, or if you run into any trouble, please post back here and I will be happy to help you.

**Comment by Robadob** [comment]
Hi @tobyhodges,

I've now setup the [fork](https://github.com/carpentries-incubator/pando-python), and pushed an extra commit that hides the disables the most obvious Sheffield stuff (there might be some in within the lesson content, but I'll review that within the near future).

The course is now live [here](https://carpentries-incubator.github.io/pando-python/). Although pushing the commit to remove Sheffield branding didn't automatically trigger the GH actions, so not sure if I've broken something during the fork. I've manually triggered a repeat of the initial deploy action, which is currently sitting in queue.

I've added some initial tags to the repo, I also added `profiling`, which is not found in the [official tag list](https://docs.google.com/spreadsheets/d/1KkmBtCu4PaNb5nzJAD82UHcfHQlaPY84qPVxw8WO8es/edit?gid=265928257#gid=265928257), but it seems most appropriate to me.

I think that's everything, I just need to work through my backlog of suggestions/improvements now but this has hopefully given me a kick.

**Comment by tobyhodges** [comment]
Thanks @Robadob. 

> Although pushing the commit to remove Sheffield branding didn't automatically trigger the GH actions, so not sure if I've broken something during the fork.

By default, Actions workflows are not enabled on forks. I have unpublished your GH Pages site for now. If you cancel & delete [the pages build and deployment workflows currently queued](https://github.com/carpentries-incubator/pando-python/actions/runs/10883072958) on the repository, you should see a button saying something like _"I understand my workflows, go ahead and enable them"_. If you push that, the list of Workbench workflows will appear. You can then run the "Build and Deploy Lesson" workflow to set the site building (or push another commit to `main`, which will trigger the Action). No need to re-activate GitHub Pages -- the workflows should do that automatically.

I will go ahead and close this issue now that you have the fork setup, but feel free to post back here if you have any further questions.

**Comment by Robadob** [comment]
Thanks @tobyhodges 

I think it's stuck in a bad state. When I try to "cancel run" it fails.

![image](https://github.com/user-attachments/assets/add7272a-bcf5-4123-92b9-7a85a89c6eb3)

>  you should see a button saying something like "I understand my workflows, go ahead and enable them".

I don't recall seeing that before I requested a rerun of the initial build/deploy job that succeeded.

I've placed a GitHub support ticket, will update when I get a response or it's resolved.

**Comment by Robadob** [comment]
Small update.

I've had about 3 days of back and forth with GitHub support, and they're no closer to being able to resolve it.

I've created a second fork, and that seems happy: https://github.com/carpentries-incubator/pando-python2

I'll delete the broken fork and rename the new one, just waiting for GH support to confirm whether I should leave the broken one in some form so that they can have a developer actually investigate whatever error state it's in.
