### ISSUE TITLE
[Proposal]: Reproducible Computational Environments Using Containers: Introduction to Kubernetes

### ISSUE THREAD

**Issue by cbohn4** [carpentries-incubator/proposals#202]
### 1. Lesson Topic

Introduction to Kubernetes

### 2. Lesson Language

English

### 3. Draft materials

https://github.com/carpentries-incubator/kubernetes-introduction

### 4. Requirements for existing materials

- [X] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [X] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [ ] I need a new repository created

### 6. Transfer existing repository

- [X] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@cbohn4 

### 8. Info/Questions

This is a lesson I have transferred ownership to the carpentries-incubator already and would need permissions to further work on. 
The fork I made of the original repository that was transferred is https://github.com/cbohn4/kubernetes-introduction. 
The lesson provides a basic introduction to Kubernetes for research computing. It is still in development, but it may be taught in January as part of a workshop covering the [National Research Platform](https://nationalresearchplatform.org/).  Feedback will be used to further the lesson contents.

**Comment by tobyhodges** [comment]
Hi @cbohn4, I have granted you Admin access and also included you in a maintainer team, so that you can add new maintainers in the future.

While we keep the criteria for inclusion in the Incubator to a minimum, I still need to perform a few checks before accepting a project here. Next time, please open an issue here before transferring the repository into the Incubator. 

I will close this now but will still receive notifications so please post back here with any questions.
