### ISSUE TITLE
Packaging and Publishing Python projects

### ISSUE THREAD

**Issue by brownsarahm** [carpentries-incubator/proposals#23]
> 1. What is the topic of your lesson or lesson proposal?

Publishing and sharing python data science projects

> 2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

Yes.
repo: https://github.com/brownsarahm/python-packaging-publishing
rendered: https://brownsarahm.github.io/python-packaging-publishing/

> 3. Do your materials conform to our [Code of Conduct][coc]?

yes

> 4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? 

Yes, but an out of date version of the styles repository, are there docs for how to update?

> 5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

> 6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Write access][access-levels] to the repository. 

yes

> 7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Write access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later. 

none yet

> 8. Any other information you would like us to have or questions you have for us?

this addresses some of the topics in #2

Thank you for sharing your lesson with The Carpentries community!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by ErinBecker** [comment]
Hi @brownsarahm - thanks for the lesson proposal! I've just sent you an invite to join the carpentries-incubator organization. Once you accept, you will have permission to transfer your repo to this org. 

I know I really *should* know the answer to your question about updating to the newest template version, but I'm not finding that documentation at the moment. @fmichonneau - could you please point us in the right direction? (I'm making a note to myself to put this info in the Lesson Maintenance section of the Handbook!). 

It's totally ok to transfer the repo over without updating the template, btw. As long as the repo uses some version of the template, it can be hosted here. We're working on upgrading our system to use remote themes so that we can reduce the burden on Maintainers of updating their lesson styling and do all of that automatically.

**Comment by brownsarahm** [comment]
Thanks! @ErinBecker!

When I moved it, I lost admin privileges, I can't change the link at the top anymore.

**Comment by ErinBecker** [comment]
Good catch @brownsarahm! I've updated the link -your lesson renders at https://carpentries-incubator.github.io/python-packaging-publishing/ now! We're testing out the Incubator model with Write access for the original lesson authors, but might need to change to Admin level access. Please do let me know if you run into other problems that you need Admin access for. This info will be really useful as we refine our model for the Incubator. 

In the meantime, anyone you'd like me to add as a Maintainer to the repo?

**Comment by ErinBecker** [comment]
Ah, I see that you already answered that question above! In that case, I'm going to go ahead and close this issue. Please let me know if you need anything!
