### ISSUE TITLE
Metagenomics and Pangenomics #lesson-idea 

### ISSUE THREAD

**Issue by nselem** [carpentries-incubator/proposals#53]
1. What is the topic of your lesson or lesson proposal?
Analysis of metagenomics and pangenomics data

I have enjoyed the Software Carpentry's Genomic lesson, and I think we can go further and develop metagenomics and pangenomics lessons. Since in my work I need to teach both of them in this semester, I am going to start developing this idea, and I would be glad to have collaborators. I am planning to use AnVio as the main software because it has very good tutorials and public data, and  their developers like the lesson idea. I am planning to include some other bioinformatics tools. To simplify installation process I liked the idea of use AMI machines just like in the genomic lesson, so, I want to develop a docker, based on Anvio docker to really make this lesson happen.

**Comment by tobyhodges** [comment]
Thanks for the lesson idea, @nselem. You said you plan to begin working on these materials - do you already have a repository where you're doing that? If so, would you like me to help you transfer it over to the Incubator? Or, if you don't have a repository for your lesson yet, would you like me to create one for you here (setup to use the Carpentries lesson template)? A repository in the Incubator might be easier for other community members (and potential collaborators!) to find.

**Comment by nselem** [comment]
Hello,
Yes, I started the repo from https://github.com/BetterLabMx/metagenomics, it does not have content yet, jus the title, but I will be working on it. Please transfer the repo to the Incubator.
Nelly

**Comment by tobyhodges** [comment]
@nselem you should have received an invitation to join the **carpentries-incubator** organisation. Once you've accepted that, you should be able to initiate the repo transfer from the settings page of your lesson repository. Once that's done, I'll take care of a few things to get the lesson ready for listing on our [Community Lessons page](https://carpentries.org/community-lessons/), and you can go ahead and continue developing the material in the Incubator.

**Comment by BetterLabMx** [comment]
Maybe you need to invite me with this account, @BetterLabMx, because is where I started the repo. I already joined the carpentries-incubator as Nelly Selem, but as Nelly I don't have access to the settings page.

**Comment by tobyhodges** [comment]
Done 👍

**Comment by BetterLabMx** [comment]
Me too, Done

**Comment by tobyhodges** [comment]
Thanks! I've updated the tags on [the new repository](https://github.com/carpentries-incubator/metagenomics), so the lesson should appear on our [Community Developed Lessons page](https://carpentries.org/community-lessons/) soon. I'll also submit a Pull Request in the next day or so, to update the lesson to use the latest version of The Carpentries theme so that it's consistent with other lessons in the Incubator. Finally, I'll be in touch again soon so I can learn more about your plans for the lesson and how I and the rest of the Carpentries core team can support you in developing this material.

I'll close this Issue now but feel free to reopen if you run into any trouble with the new repository or if you have any questions.

**Comment by nselem** [comment]
Please could you alse add as contributor to @EdderDaniel he is interested in collaborating

**Comment by BetterLabMx** [comment]
Hello Toby

Please could you alse add as contributor to @EdderDaniel
<https://github.com/EdderDaniel> to the metagenomics lesson he is
interested in collaborating and we are starting to work in the lesson

Thanks

Nelly
