### ISSUE TITLE
HPC-Carpentry: HPC Intro

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/proposals#65]
Thank you for your interest in developing and sharing lesson materials! To submit lesson materials or suggest a topic for future curricular development, please answer the questions below. Our Curriculum Development Team will follow up to suggest next steps in your lesson's trajectory. Questions? Please email team@carpentries.org.

1. What is the topic of your lesson or lesson proposal?

    A basic introduction to high-performance computing and, more specifically, interacting with HPC cluster tools, queues, and workflows.

2. Do you already have a draft of your lesson? You're welcome to share materials at any stage of development. If you already have drafted materials, please include a link.

    Yes.

3. Do your materials conform to our [Code of Conduct][coc]?

    Yes.

4. Are your materials already on GitHub and do they use The Carpentries [lesson template][lesson-template]? (you can visit [our lesson example](https://carpentries.github.io/lesson-example/) to learn more about how to use our template).

    Yes, and Yes. We use the `carpentries-style` rather than hauling all the boilerplate around.

5. If you answered "No" to either part of question 4, would you like our Curriculum Team to create a repository for you in The Carpentries Incubator?

    (No.)

6. If you answered "Yes" to both parts of question 4, would you like to transfer your repository to The Carpentries Incubator? You will have [Admin access][access-levels] to the repository.

    Yes.

7. If you answered "Yes" to either question 5 or 6, list the GitHub handles for people who should have [Maintain access][access-levels] to your lesson. If you don't know how to answer this question, don't worry! We can always add collaborators later.

    Active members of [@hpc-intro-maintainers](https://github.com/orgs/hpc-carpentry/teams/hpc-intro-maintainers/members), *viz*:

   - [x] @ChristinaLK
   - [ ] @CarrieBrown
   - [x] @ErinBecker 
   - [x] @annajiat
   - [x] @colinsauze
   - [x] @willfurnass
   - [ ] @mikerenfro
   - [ ] @ocaisa
   - [x] @psteinb
   - [ ] @reid-a
   - [x] @tkphd

8. Any other information you would like us to have or questions you have for us?

    @tobyhodges has been most helpful holding our hands through this delicate period.

Thank you for sharing your lesson with The Carpentries community!

    No, thank *you*!

[access-levels]: https://help.github.com/en/articles/repository-permission-levels-for-an-organization
[coc]: https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view
[lesson-template]: https://github.com/carpentries/styles

**Comment by tobyhodges** [comment]
Thank you for submitting this lesson to the Incubator, @tkphd. I've invited you and your collaborators to the carpentries-incubator organization on GitHub, in the _hpc-intro-maintainers_ team. After accepting that invitation, you should be able to transfer the repository from the hpc-carpentry namespace to carpentries-incubator. Please let me know if you have any trouble doing that, or if you have any questions about the process.

Once you've transferred the repository, you might choose to:

1. adjust the value of the `carpentry` parameter in the lesson `_config.yml` to `incubator`. this will add the appropriate banner and styling to the lesson pages
2. opt into listing issues from the lesson on [the Help Wanted page on The Carpentries website](https://carpentries.org/help-wanted-issues/)
3. adjust the GitHub repository topics for your lesson, so that it is listed correctly on the [Community Developed Lessons page on The Carpentries website](https://carpentries.org/community-lessons/). More info about choosing these topics can be found in [the Incubator appendix to the Curriculum Development Handbook](https://cdh.carpentries.org/the-carpentries-incubator.html#topic-tags). 

I can help with any of the above so please go ahead and ping me if anything is unclear.

**Comment by tobyhodges** [comment]
I forgot to mention above: you will also need to update your URLs.

Lesson pages URL is now https://carpentries-incubator.github.io/hpc-intro/

... and you can update the remote url for your local versions with git. the examples below assumes this remote is called `origin` on your local system.

```bash
git remote set-url origin git@github.com:carpentries-incubator/hpc-intro.git # with SSH
git remote set-url origin https://github.com/carpentries-incubator/hpc-intro.git # with HTTPS
```

**Comment by tkphd** [comment]
Done! (Other folks with local clones of the repo will have to change their own remote URLs.)

**Comment by tobyhodges** [comment]
I am going to close this issue now that most of the transfer process seems to have gone smoothly. But please feel free to post back here or ping me in another issue if you run into any trouble or have any further questions. Great to have you aboard!
